const ServicesGallery = [
    
   { 
    id:1,
    title: "Prewedding",
    leftimage1: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651620/Home_ourgallery/Prewedding/pre8_rvxfpt.png',
    leftimage2: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651620/Home_ourgallery/Prewedding/pre7_j281cy.png',
    leftimage3: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651620/Home_ourgallery/Prewedding/pre9_n8zaum.png',
    leftimage4: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651619/Home_ourgallery/Prewedding/pre2_g3qq6e.png',
    centerimage: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651618/Home_ourgallery/Prewedding/pre18_bqchen.png',
    leftimage5: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651618/Home_ourgallery/Prewedding/pre20_v2uces.png',
    leftimage6: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651618/Home_ourgallery/Prewedding/pre11_cz1bqh.png',
    leftimage7: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651618/Home_ourgallery/Prewedding/pre1_f0d5ax.png',
    leftimage8: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651624/Home_ourgallery/Prewedding/pre22_dx1liq.png',
},
{
    id:2,
    title: "Weddings",
    leftimage1: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651826/Home_ourgallery/Wedding/Weeding_service3_h4co26.png',
    leftimage2: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651825/Home_ourgallery/Wedding/Weeding_service7_vjloee.png',
    leftimage3: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651825/Home_ourgallery/Wedding/Weeding_service14_slan7h.png',
    leftimage4: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651823/Home_ourgallery/Wedding/Weeding_service8_o7gblh.png',
    centerimage: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651824/Home_ourgallery/Wedding/Weeding_service10_ghvw2q.png',
    leftimage5: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651822/Home_ourgallery/Wedding/Weeding_service20_rge4il.png',
    leftimage6: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651822/Home_ourgallery/Wedding/Weeding_service26_gdyhz1.png',
    leftimage7: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651821/Home_ourgallery/Wedding/Weeding_service22_pwwdk7.png',
    leftimage8: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707651821/Home_ourgallery/Wedding/Weeding_service21_g2c59r.png',
    },
    
{   
    id:3,
    title: "Engagement",
    leftimage1: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement20_wmglob.png',
    leftimage2: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652362/Home_ourgallery/Engagement/Engagement44_hyhwth.png',
    leftimage3: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement20_wmglob.png',
    leftimage4: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement47_elzvgc.png',
    centerimage: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement20_wmglob.png',
    leftimage5: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652361/Home_ourgallery/Engagement/Engagement32_ahwxll.png',
    leftimage6: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement1_r83zne.png',
    leftimage7: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652360/Home_ourgallery/Engagement/Engagement2_xfr3it.png',
    leftimage8: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707652359/Home_ourgallery/Engagement/Engagement10_mqyn9x.png',
},
{   
    id:4,
    title: "Birthday",
    leftimage1: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653141/Home_ourgallery/Birthday/birthdaythirtynine_lfljpe.png',
    leftimage2: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653141/Home_ourgallery/Birthday/birthdaythirtynine_lfljpe.png',
    leftimage3: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653140/Home_ourgallery/Birthday/birthdayfourtyeight_t7jnnu.png',
    leftimage4: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653138/Home_ourgallery/Birthday/birthdayeightythree_xehoo9.png',
    centerimage: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653140/Home_ourgallery/Birthday/birthdayninteyone_cnbsfe.png',
    leftimage5: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653138/Home_ourgallery/Birthday/birthdayfiftynine_iz0i8h.png',
    leftimage6: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653138/Home_ourgallery/Birthday/birthdaytwentyfour_k1scyv.png',
    leftimage7: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653138/Home_ourgallery/Birthday/birthday17_cjk8hu.png',
    leftimage8: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653138/Home_ourgallery/Birthday/birthday1_ixyuul.png',
},
{   
    id:4,
    title: "Baby Shower",
    leftimage1: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653749/Home_ourgallery/Babyshower/baby6_lqalq6.png',
    leftimage2: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653716/Home_ourgallery/Babyshower/baby14_nxxoec.png',
    leftimage3: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653747/Home_ourgallery/Babyshower/baby38_vkqyjd.png',
    leftimage4: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653746/Home_ourgallery/Babyshower/baby35_zpderw.png',
    centerimage: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653745/Home_ourgallery/Babyshower/baby30_sj602w.png',
    leftimage5: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653744/Home_ourgallery/Babyshower/baby27_d5if8f.png',
    leftimage6: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653743/Home_ourgallery/Babyshower/baby24_pincsb.png',
    leftimage7: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653743/Home_ourgallery/Babyshower/baby20_ebvqho.png',
    leftimage8: 'https://res.cloudinary.com/dqnlbtgdl/image/upload/v1707653745/Home_ourgallery/Babyshower/baby21_ffdjbb.png',
},

]
export default ServicesGallery